version: '3.8'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
    networks:
      - mebenet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mebenet

  backend:
    build:
      context: /home/root/test_servere/BE/Project_MeBe
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://database:1433;databaseName=me_be_test;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_DATASOURCE_PASSWORD: YourStrong@Passw0rd
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - database
      - redis
    ports:
      - "8081:8080"
    networks:
      - mebenet

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - /home/root/test_servere/FE_MeBeReact/app-project-master/build:/usr/share/nginx/html
      - /home/root/test_servere/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mebenet

networks:
  mebenet:
    driver: bridge
